Implements log print
victorhenriquetx/mc861-nesemulator pull request #6
Opened 2019-09-26 03:08 UTC by rogerio-gmeirelles

Implements log print like it was specified here:
https://github.com/AlissonLinhares/nesemu/blob/master/log/brk.log

Note that instructions that read memory will also need to print
` | MEM[address] = value`

2019-09-26 03:24 UTC, gabrielpreviato commented
Hey @rogerio-gmeirelles thanks for the PR. What are your thoughts in moving the prints statements to another method? Something like `def log(self, memory=None)`? We can call this method after the decode_instruction (or before, I don't record the correct order).

The only change that will be needed in the decode_instructions is returning if the memory was accessed or not.

2019-09-26 03:28 UTC, gabrielpreviato requested changes
I think we should move the print statements to another method.

2019-09-27 02:00 UTC, gabrielpreviato submitted a review, later dismissed
Due to not having much time right now, I think we can keep with this implementation. We can make improvements later.

2019-09-27 02:24 UTC, victorhenriquetx commented on Processor.py
> +            print('| p[NV-BDIZC] = ' + str(self.FLAGS.get_N()) + str(self.FLAGS.get_V()) + '1' + str(self.FLAGS.get_B()) + str(self.FLAGS.get_D()) + str(self.FLAGS.get_I()) + str(self.FLAGS.get_Z())
Testei aqui e o método get_"FLAG"() printa o valor inteiro da flag, na minha branch eu criei os métodos is_"FLAG"(self) que retorna o bit da flag

2019-09-27 03:52 UTC, gabrielpreviato commented on Processor.py
> +            print('| p[NV-BDIZC] = ' + str(self.FLAGS.get_N()) + str(self.FLAGS.get_V()) + '1' + str(self.FLAGS.get_B()) + str(self.FLAGS.get_D()) + str(self.FLAGS.get_I()) + str(self.FLAGS.get_Z())
Actually I think this was a problem with this implementation, at least I think @rogerio-gmeirelles intentions were to return 1 or 0.

2019-09-27 03:57 UTC, gabrielpreviato approved these changes

2019-09-27 23:00 UTC, closed without merging